const formGenerator = require('./formGenerator/formGenerator');
const prompter = require('./prompter');


/*  
* feeds the command line prompter with the form prompt objects,
* generated by the formGenerator from the form data.
*/

module.exports = (formData) => {
    return prompter(
        formGenerator(Object.keys(formData),formData)
    )
};