const middleware = require('./middleware');


/*  
* feeds the command line prompter with the form prompt objects,
* generated by the formGenerator from the form data.
*/

module.exports = (jsonFormData) => {
    return middleware(jsonFormData);
};